name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm test
    - name: Set environment variables
      run: |
        echo "ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "CLIENT_ID=${{ secrets.CLIENTID }}" >> $GITHUB_ENV
        echo "CLIENT_SECRET=${{ secrets.CLIENTSECRET }}" >> $GITHUB_ENV
        echo "ADMIN_ID=${{ secrets.ADMIN_ID }}" >> $GITHUB_ENV
        echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV
    - run: pm2 restart backendserver
